version: "2.1"
services: 
  alfa:
    build: .
    container_name: alfa
    hostname: alfa
    user: root
    ports:
      - "10012:10012"
      - "10013:10013"
      - "10014:10014"
    volumes:
      /opt/corda/nodes/alfa/:/opt/corda/nodes/alfa/

  barclays:
    build: .
    container_name: barclays
    hostname: barclays
    user: root
    ports:
      - "10022:10022"
      - "10023:10023"
      - "10024:10024"
    volumes:
      /opt/corda/nodes/barclays/:/opt/corda/nodes/barclays/

  notary:
    build: .
    container_name: notary
    hostname: notary
    user: root
    ports:
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
    volumes:
      /opt/corda/nodes/notary/:/opt/corda/nodes/notary/

