version: "2.1"
services: 
  alfa:
    build:
      context: .
      dockerfile: ./alfa/Dockerfile
    container_name: alfa
    hostname: alfa
    user: root
    networks:
      app_net:
        ipv4_address: 34.91.190.250
 
    ports:
      - "10012:10012"
      - "10013:10013"
      - "10014:10014"
    volumes:
      - /home/tatjana_frank/blockchain_demo/corda-docker/alfa:/opt/corda/nodes/alfa/

  barclays:
    build:
      context: .
      dockerfile: ./barclays/Dockerfile
    container_name: barclays
    hostname: barclays
    user: root
    networks:
      app_net:
        ipv4_address: 34.91.190.250

    ports:
      - "10022:10022"
      - "10023:10023"
      - "10024:10024"
    volumes:
      - /opt/corda/nodes/barclays/:/opt/corda/nodes/barclays/

  notary:
    build:
      context: .
      dockerfile: ./notary/Dockerfile
    container_name: notary
    hostname: notary
    user: root
    networks:
      app_net:
        ipv4_address: 34.91.190.250

    ports:
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
    volumes:
      - /opt/corda/nodes/notary/:/opt/corda/nodes/notary/

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 34.91.190.250/24
          gateway: 34.91.190.250